# -----------------------------------------
# Docker Swarm Logging Stack yaml
# Owner: Ahmet AKSIT <ahmetaksit@gmail.com>
# links: https://github.com/dockerAA/logging
#------------------------------------------
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - xpack.security.enabled=false
    deploy:
      resources:
        reservations:
          memory: 3000M
        limits:
          memory: 3500M
      placement:
        constraints: [node.role == manager]
    volumes:
      # - /data/elasticsearch/data:/usr/share/elasticsearch/data
      - type: volume
        source: elasticsearch-data
        target: /usr/share/elasticsearch/data
        volume:
           nocopy: true
    # ports:
    #   - 9200:9200
    networks:
      - logging

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.16.18.11,rw
      device: ":/docker01_mcA/docker/volumes/logging/elasticsearch-data"

networks:
  logging:
#    external: true
